# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build and test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: "3.1.45"
          actions-cache-folder: "emsdk-cache"
      - run: npm ci
      - run: npm run build
      - run: npm run test:root
      - uses: actions/upload-artifact@v3
        with:
          name: libpg-query-wasm
          path: packages/libpg-query-wasm/dist

  test:
    needs: [build]
    timeout-minutes: 10
    strategy:
      matrix:
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
        node-version: [18.x, 20.x]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: libpg-query-wasm
          path: packages/libpg-query-wasm/dist
      - run: npm run test:workspaces
