name: Publish libpg-query-wasm

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Type of version bump"
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
          - same

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "true"
      - name: Use Node.js 20.x
        uses: actions/setup-node@v2
        with:
          node-version: "20.x"
          cache: "npm"
      - name: Install Emscripten
        uses: mymindstorm/setup-emsdk@v12
        with:
          version: "3.1.45"
      - run: npm ci
      - run: npm run build
      - run: npm version ${{ github.event.inputs.version }}
        if: github.event.inputs.version != 'same'
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: git push --follow-tags
        if: github.event.inputs.version != 'same'
