name: Version a package

on:
  workflow_dispatch:
    inputs:
      version:
        description: Type of version bump
        required: true
        type: choice
        options:
          - major
          - minor
          - patch
      package:
        description: Package to version
        required: true
        type: choice
        options:
          - libpg-query-wasm

permissions:
  contents: write

jobs:
  version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "npm"
      - run:
          ./scripts/version.sh ${{github.event.inputs.package}}
          ${{github.event.inputs.version}}
